name: nsmeteo
description: Une application météo en Flutter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path: ^1.8.0
  sqflite: ^2.0.2+1
  http: ^0.13.4
  intl: ^0.17.0
  carousel_slider: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.


  uses-material-design: true

  assets:

  # Icones
    - assets/images/icones/calendar.png
    - assets/images/icones/carte.png
    - assets/images/icones/horloge-murale.png
    - assets/images/icones/liste.png
    - assets/images/icones/loupe.png
    - assets/images/icones/plus.png

  # Meteo Icones
    - assets/images/meteoIcones/cloudysun.png
    - assets/images/meteoIcones/rain.png
    - assets/images/meteoIcones/snow.png
    - assets/images/meteoIcones/sun.png
    - assets/images/meteoIcones/water.png
    - assets/images/meteoIcones/wind.png

  #Background GIF
    - assets/images/background/thunder.gif
    - assets/images/background/cloudy.gif
    - assets/images/background/cloudysun.gif
    - assets/images/background/rain.gif
    - assets/images/background/snow.gif
    - assets/images/background/sunny.gif


  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
